import play.sbt.routes.RoutesKeys
import sbt.Def
import scoverage.ScoverageKeys

ThisBuild / scalaVersion := "3.7.4"

lazy val appName: String = "soft-drinks-industry-levy-registration-frontend"

lazy val root = (project in file("."))
  .enablePlugins(PlayScala, SbtDistributablesPlugin)
  .disablePlugins(JUnitXmlReportPlugin) // Required to prevent https://github.com/scalatest/scalatest/issues/1427
  .settings(inConfig(Test)(testSettings):_*)
  .settings(
    majorVersion := 0,
    libraryDependencySchemes += "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always
  )
  .settings(ThisBuild / useSuperShell := false)
  .settings(
    name := appName,
    RoutesKeys.routesImport ++= Seq(
      "models._",
      "uk.gov.hmrc.play.bootstrap.binders.RedirectUrl"
    ),
    TwirlKeys.templateImports ++= Seq(
      "play.twirl.api.HtmlFormat",
      "play.twirl.api.HtmlFormat._",
      "uk.gov.hmrc.govukfrontend.views.html.components._",
      "uk.gov.hmrc.hmrcfrontend.views.html.components._",
      "uk.gov.hmrc.hmrcfrontend.views.html.helpers._",
      "uk.gov.hmrc.hmrcfrontend.views.config._",
      "views.ViewUtils._",
      "models.Mode",
      "controllers.routes._",
      "viewmodels.govuk.all._"
    ),
    PlayKeys.playDefaultPort := 8706,
    ScoverageKeys.coverageExcludedFiles := "<empty>;Reverse.*;.*handlers.*;.*components.*;" +
      ".*Routes.*;.*viewmodels.govuk.*;",
    ScoverageKeys.coverageMinimumStmtTotal := 88,
    ScoverageKeys.coverageFailOnMinimum := true,
    ScoverageKeys.coverageHighlighting := true,
    scalacOptions ++= Seq(
      "-feature",
      "-Wconf:msg=Flag.*repeatedly:s",
      "-Wconf:msg=unused explicit parameter*:s",
      "-Wconf:msg=unused private member*:s",
      "-Wconf:msg=unused implicit parameter*:s",
      "-Wconf:msg=unused local definition*:s",
      "-Wconf:msg=unused patterns*:s",
      "-Wconf:msg=unused import*:s",
      "-Wconf:msg=exhaustive*:s"
    ),
    libraryDependencies ++= AppDependencies.all(),
    retrieveManaged := true,
    // concatenate js
    Concat.groups := Seq(
      "javascripts/application.min.js" ->
        group(
          Seq(
            "javascripts/app.js"
          )
        )
    ),
    // prevent removal of unused code which generates warning errors due to use of third-party libs
    uglifyCompressOptions := Seq("unused=false", "dead_code=false"),
    pipelineStages := Seq(digest),
    // below line required to force asset pipeline to operate in dev rather than only prod
    Assets / pipelineStages := Seq(concat, uglify),
    // only compress files generated by concat
    uglify / includeFilter := GlobFilter("application.js")
  )

lazy val testSettings: Seq[Def.Setting[?]] = Seq(
  fork := true,
  unmanagedSourceDirectories += baseDirectory.value / "test-utils"
)

lazy val it = (project in file("it"))
  .enablePlugins(PlayScala)
  .disablePlugins(SbtDistributablesPlugin)
  .dependsOn(root % "test->test")
  .settings(
    majorVersion := 0,
    Test / scalacOptions := (Test / scalacOptions).value.distinct,
    Test / unmanagedSourceDirectories := Seq(baseDirectory.value),
    Test / unmanagedResourceDirectories := Seq(baseDirectory.value / "resources"),
    Test / parallelExecution := false,
    Test / fork := true,
    Test / javaOptions += "-XX:+EnableDynamicAgentLoading"
  )